language: node_js
node_js:
  - node
script:
  - ng build
deploy:
  provider: heroku
  api_key:
    secure: k6Q9YIMuQ9aogBvCZiPGd4o9eoxFJtHkATsXK3Wsy//005LGvfOE4kXfeqUU+6O51qns7qcwC5tWR6uNt44nUWPw7ckFA5csauSolCIwYf5efumRYasr2ZsteymfsO9aU50Py5/OizeQPgO/z8KqKswfZm5MjCtH7ODC9hvzE6JbxSwrc6Iwb/ZMDvN3hRBNTXMxQlkGNPTJYq6/tjf21tG1Qt74arhKExfE6TkObmaqu3E0AocwXtQsyUb64K3iOjGxCiu8zJYhhcOgt5C36m4B3vQg9/NO47UOCiCFGkddpJQJ9h80QbPgB7pNgabv7oisx85Ev/lckAbwh1EcLpOAjGfMi/JeAT2QMNttIBTWnjCcNCYO+GJjpT8jCKO9CyUlH832Ecd2XXdmtfeDI98X/6jTdLiEq6w0CXxyAHqbqBZkCHYr8HQHbzQbfejun9IAHbKCtPqIEcFfKICd2DK326tN2w5pOhCuTzDOkgPp+hyHlZsAQj5OYHeR3wbSiOlv+TJufOjFi/2ohCH3Xpgm7MX7MJgeqGL5NPhnfjcohhFcBCzqJbxUCftv33HSb6Fi2YcCOKjtPSZw6z3PGmh9mIPFAtdenZIILvLYrDLmKcnq1ZnnPsEh1wrbHeUkgXoGGZti6kFPtq6ot25mssfKLKcUrPz59M8vTM+bAS0=
