sudo: required
language: node_js
node_js:
  - node
services:
  - docker
script:
  - ng build
  - docker build -t registry.heroku.com/catandice/web .
  - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD" registry.heroku.com
  - docker push registry.heroku.com/catandice/web
